name: Android CI (Old-style, Android 8)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Download Gradle 8.2.1
      - name: Download Gradle 8.2.1
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2.1-bin.zip -O gradle-8.2.1.zip
          unzip gradle-8.2.1.zip -d gradle-dist
          chmod +x gradle-dist/gradle-8.2.1/bin/gradle

      # 4️⃣ Generate Gradle wrapper if missing
      - name: Generate Gradle wrapper if missing
        run: |
          if [ ! -f ./gradlew ]; then
            echo "Gradle wrapper not found, generating..."
            ./gradle-dist/gradle-8.2.1/bin/gradle wrapper --gradle-version 8.2.1
          else
            echo "Gradle wrapper already exists."
          fi

      # 5️⃣ Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 6️⃣ Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 7️⃣ Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zaticker-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
