name: Android CI (Generate Wrapper from Local Gradle)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make sure local gradle is executable
        run: chmod +x ./gradle

      - name: Generate Gradle Wrapper using local gradle
        run: ./gradle wrapper

      - name: Grant execute permission for generated wrapper
        run: chmod +x ./gradlew

      - name: Build Debug APK using wrapper
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Zaticker-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
